export interface DutyAssignment {
  teacherId: string;
  roomId: string;
}

export interface ManualDutyOverride {
  teacherId: string;
  roomId: string;
  previousRoomId?: string;
  at: string;
  forced: boolean;
}

export interface DutyConflict {
  id: string;
  type: 'duplicate_teacher' | 'room_overstaffed' | 'own_branch_violation';
  severity: 'medium' | 'high';
  teacherId?: string;
  roomId?: string;
  description: string;
}

export interface DutyValidationReport {
  generatedAt: string;
  totalRoomsNeeded: number;
  roomsFullyStaffed: number;
  balanceScore: number; // 0-100: average fulfillment of each room's own capacity-derived target
  conflicts: DutyConflict[];
  allHardConstraintsPassed: boolean;
}

export interface DutyRoster {
  id: string;
  examId: string;
  generatedAt: string;
  seed: number;
  /** Invigilators per room = ceil(room's available seats / seatsPerInvigilator), min 1. */
  seatsPerInvigilator: number;
  /** roomId -> required invigilator count, computed at generation time so the roster is self-explanatory later. */
  roomDutyTargets: Record<string, number>;
  /** Optional workload caps - unset/0 means no limit. */
  maxDutiesPerDay?: number;
  maxDutiesTotal?: number;
  avoidOwnBranchInvigilation: boolean;
  assignments: DutyAssignment[];
  manualOverrides: ManualDutyOverride[];
  unassignedTeacherIds: string[];
  understaffedRoomIds: string[];
  validationReport: DutyValidationReport;
  version: number;
  /** Set when generated by a duty window (fair distribution across a date range). */
  windowId?: string;
  /** The seat allocation this roster was sized from - used to flag a roster as stale if seating is regenerated. */
  basedOnAllocationId?: string;
  /**
   * 'students': only rooms that actually have students get duty, sized by students seated
   * (seatsPerInvigilator then means students per invigilator). 'seats': legacy capacity-based sizing.
   */
  basis?: 'seats' | 'students';
}

/** Per-teacher override inside a duty window. Unset fields fall back to the window defaults. */
export interface DutyTeacherQuota {
  min?: number;
  max?: number;
  /** Exempt teachers get no duty in this window (e.g. HOD, on leave). */
  exempt?: boolean;
}

/**
 * A date range (e.g. "Sessional 1", Nov 1 - Nov 7) with the rules duties are
 * shared out under. Every exam whose date falls inside it takes part.
 */
export interface DutyWindow {
  id: string;
  name: string;
  startDate: string; // YYYY-MM-DD, inclusive
  endDate: string; // YYYY-MM-DD, inclusive
  /** Invigilators per occupied room = ceil(students in room / studentsPerInvigilator), min 1. */
  studentsPerInvigilator: number;
  /** Duties per teacher across the whole window. Unset = no limit / no minimum. */
  defaultMinDuties?: number;
  defaultMaxDuties?: number;
  /** Max sessions one teacher may be on duty in a single day. Unset = no limit. */
  maxPerDay?: number;
  avoidOwnBranchInvigilation: boolean;
  perTeacher: Record<string, DutyTeacherQuota>;
}
