/**
 * Shared logic behind scripts/sync-backend-vendor.mjs and
 * scripts/sync-frontend-vendor.mjs. See those files for the "why".
 */
import { readdir, mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname, relative, extname } from 'node:path';

const SPECIFIER_RE = /(['"])@exam-allocator\/([a-z-]+)\1/g;
const SOURCE_EXTENSIONS = ['.ts', '.tsx'];

function banner(pkgName) {
  return (
    `// AUTO-GENERATED by the vendor sync script from packages/${pkgName}/src - do not edit here.\n` +
    `// Edit the source in packages/${pkgName} instead, then re-run that script to update this copy.\n`
  );
}

async function walkSourceFiles(dir, exclude = []) {
  const entries = await readdir(dir, { withFileTypes: true });
  let files = [];
  for (const entry of entries) {
    if (exclude.includes(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files = files.concat(await walkSourceFiles(full, exclude));
    } else if (SOURCE_EXTENSIONS.includes(extname(entry.name))) {
      files.push(full);
    }
  }
  return files;
}

function computeRelativeImport(fromDir, vendorRoot, pkgName) {
  const targetDir = join(vendorRoot, pkgName);
  let rel = relative(fromDir, targetDir).split('\\').join('/');
  if (!rel.startsWith('.')) rel = './' + rel;
  return `${rel}/index.js`;
}

/** Rewrites every `@exam-allocator/<pkg>` specifier in `content` to a relative path into `vendorRoot`. */
export function rewriteImports(content, currentFileDir, vendorRoot) {
  return content.replace(SPECIFIER_RE, (_match, quote, pkgName) => {
    return `${quote}${computeRelativeImport(currentFileDir, vendorRoot, pkgName)}${quote}`;
  });
}

/** Copies each package's src/ into `<vendorRoot>/<pkg.name>`, rewriting cross-package imports as it goes. */
export async function syncVendoredPackages(vendorRoot, packages) {
  for (const pkg of packages) {
    if (!existsSync(pkg.srcDir)) {
      console.log(`skip "${pkg.name}": ${pkg.srcDir} not found (already vendored-only, not shared anymore?)`);
      continue;
    }
    const destDir = join(vendorRoot, pkg.name);
    const files = await walkSourceFiles(pkg.srcDir, pkg.exclude ?? []);
    for (const file of files) {
      const relPath = relative(pkg.srcDir, file);
      const destPath = join(destDir, relPath);
      await mkdir(dirname(destPath), { recursive: true });
      let content = await readFile(file, 'utf-8');
      content = rewriteImports(content, dirname(destPath), vendorRoot);
      await writeFile(destPath, banner(pkg.name) + content, 'utf-8');
    }
    console.log(`synced "${pkg.name}": ${files.length} file(s) -> ${relative(process.cwd(), destDir)}`);
  }
}

/** Finds hand-written source files under `dir` that still reference an `@exam-allocator/*` specifier. */
export async function findFilesWithSpecifier(dir, exclude = []) {
  const files = await walkSourceFiles(dir, exclude);
  const matches = [];
  for (const file of files) {
    const content = await readFile(file, 'utf-8');
    SPECIFIER_RE.lastIndex = 0;
    if (SPECIFIER_RE.test(content)) matches.push(file);
  }
  return matches;
}

/** Rewrites `@exam-allocator/*` imports in hand-written (non-vendored) app files to point at vendorRoot. */
export async function rewriteConsumerFiles(filePaths, vendorRoot) {
  for (const filePath of filePaths) {
    const content = await readFile(filePath, 'utf-8');
    const rewritten = rewriteImports(content, dirname(filePath), vendorRoot);
    if (rewritten !== content) {
      await writeFile(filePath, rewritten, 'utf-8');
      console.log(`rewrote imports in ${relative(process.cwd(), filePath)}`);
    }
  }
}
